openapi: 3.0.3
info:
  title: RuBAC
  description: RuBAC
  version: 1.0.0
servers:
  - url: 'https://localhost'
    variables:
      basePath:
        default: /api/v1
paths:
  /api/v1/users:
  /api/v1/users/{userId}:
  /api/v1/users/{userId}/systemRoles:
  /api/v1/users/{userId}/systemRoles/{roleId}:
  /api/v1/teams:
  /api/v1/teams/{teamId}:
  /api/v1/teams/{teamId}/subteams:
  /api/v1/teams/{teamId}/members:
  /api/v1/teams/{teamId}/members/{memberId}:
  /api/v1/teams/{teamId}/members/{memberId}/roles:
  /api/v1/teams/{teamId}/members/{memberId}/roles/{roleId}:
